### ISSUE TITLE
Question about injectFeature function

### ISSUE THREAD

**Issue by KiminRyu** [sanogueralorenzo/Android-Kotlin-Clean-Architecture#101]
Hi! I tried to use Koin library with multi-feature modules, however, I don't know how to load koin modules properly from each features. Finally, I saw your blog post and get how to load koin modules in feature. The differences is "injectFeature"(loadFeature by lazy). I tried to load modules directly

 It works as I expected,but I don't know why it is working. So, could you explain for this?

# This Library
```kotlin
// Application
class App: Application() {
    override fun onCreate() {
        super.onCreate()

        startKoin { androidContext(this) } // it seems deprecated...
    }
}

// Modules.kt
fun injectFeature() = loadFeature

private val loadFeature by lazy {
    loadKoinModules(
        viewModelModule,
        useCaseModule,
        repositoryModule,
        dataSourceModule,
        networkModule,
        cacheModule
    )
}

// in Activity
onCreate() {
	super.onCreate()
	injectFeature()
}

```

# What I tried
```kotlin
// Application
class App: Application() {
    override fun onCreate() {
        super.onCreate()

        startKoin(this, listOf(networkModule, analyticsModule))
    }
}

// in Activity One
onCreate() {
	super.onCreate()
	loadKoinModules(listOf(oneViewModelModule))
}
// in Activity Two
onCreate() {
	super.onCreate()
	loadKoinModules(listOf(twoViewModelModule))
}

it works, however, it throws Exception like this when calling loadKoinModules again...
org.koin.error.BeanOverrideException: Try to override definition with Factory [name='OneViewModel...
```

**Comment by sanogueralorenzo** [comment]
Sorry I missed this. Don't have any notifications turned ON for these ones.

`loadKoinModules` should only be called once, that is why I have it with a by lazy top level val.

You can DM me in https://kotlinlang.slack.com/ there is also a #koin channel where you can bounce off your ideas and ask questions to more people.
