### ISSUE TITLE
Gradle KTS Build Files warning

### ISSUE THREAD

**Issue by iRYO400** [sanogueralorenzo/Android-Kotlin-Clean-Architecture#107]
Hi, just pulled project and got warning from Android Studio 3.5

![2019-08-22_15-05-57](https://user-images.githubusercontent.com/12654767/63502216-e4b77680-c4ee-11e9-99bb-60f73a5e3f0a.png)

**Comment by iRYO400** [comment]
just synced gradle manually and it's gone

**Comment by abalta** [comment]
Right now Android Studio 3.5 not supported Gradle KTS, It should be supported in 3.6

**Comment by iNoles** [comment]
> Right now Android Studio 3.5 not supported Gradle KTS, It should be supported in 3.6

Actually, it is only supported on 4.0
